version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend
  
  favorite-products-api:
    restart: always
    container_name: favorite-products-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    networks:
      - backend
    depends_on:
      - postgres
    ports:
      - "${API_PORT_HTTP}:80"
      - "${API_PORT_HTTPS}:443"

  seq:
    image: datalust/seq:latest
    container_name: seq
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y

networks:
  backend:

volumes:
  postgres-data:      